### ISSUE TITLE
Crawl mockingbird links

### ISSUE THREAD

**Issue by Skarlett** [Skarlett/coggie-bot#131]
on valid links, crawl the metadata, and inform users about it via reactions 

### Objectives
---
- [x] ability to pull metadata from link parsers #128 
- [x] fix download scrubber #130 
- [x] fork `deemix` into `deemix-min`  #130 
- [ ] use setup a static web server
- [ ] wireguard
- [ ] internal dns
